# rdfs9 rule from: http://www.w3.org/TR/2013/WD-rdf11-mt-20130723/#patterns-of-rdf-entailment-informative

prefix rdf:          <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
prefix rdfs:         <http://www.w3.org/2000/01/rdf-schema#> 

CONSTRUCT {
 ?zzz rdf:type ?yyy .
} WHERE {
 ?xxx rdfs:subClassOf ?yyy .
 ?zzz rdf:type ?xxx .
}