PREFIX ex: <http://ex.example/#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?IssueShape {
        { SELECT ?IssueShape (COUNT(*) AS ?IssueShape_c3) {
          ?IssueShape ?p ?o . 
		  FILTER (?p = ex:reproducedBy && isIRI(?o))
        } GROUP BY ?IssueShape}
        { SELECT ?IssueShape (COUNT(*) AS ?IssueShape_c4) {
          ?IssueShape ?p ?o . 
		  FILTER (?p = ex:reproducedOn && datatype(?o) = xsd:dateTime)
        } GROUP BY ?IssueShape}
        FILTER (?IssueShape_c3 = ?IssueShape_c4)
    } GROUP BY ?IssueShape HAVING (COUNT(*)=0 || COUNT(*)=1)
	