PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX sdmx-concept:  <http://purl.org/linked-data/sdmx/2009/concept#>
PREFIX sdmx-attribute: <http://purl.org/linked-data/sdmx/2009/attribute#>
PREFIX wi-onto:  <http://data.webfoundation.org/webindex/ontology/>
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX cex: <http://purl.org/weso/ontology/computex#>
PREFIX dcterms:  <http://purl.org/dc/terms/>
PREFIX wi-org: <http://data.webfoundation.org/webindex/v2013/organization/>
PREFIX wi-slice:  <http://data.webfoundation.org/webindex/v2013/slice/> 

CONSTRUCT {
	?x rdf:type qb:DataSet .
	?x cex:computation _:0 .
	_:0 rdf:type cex:NormalizeDataSet .
	_:0 cex:dataSet	?dataset .
	?x dcterms:contributor wi-org:WESO .
	?x dcterms:issued "2013-07-06" .
	?x qb:structure wi-onto:DSD .
	?x dcterms:publisher wi-onto:WebFoundation .
	?x rdfs:label "Dataset" .
	?x rdfs:comment "Dataset description" .
	?x sdmx-attribute:unitMeasure <http://dbpedia.org/resource/Year> .
	?x dcterms:title "Dataset" .
	?x qb:slice ?y .
} WHERE {
	?x rdf:type qb:Dataset .
	?x qb:slice ?y .
	FILTER(CONTAINS(str(?x), "-Normalised")) .
	BIND(URI(CONCAT("http://data.webfoundation.org/webindex/v2013/dataset/", CONCAT(STRAFTER(STRBEFORE(str(?x), "-Normalised"), "http://data.webfoundation.org/webindex/v2013/dataset/"), "-Sorted"))) AS ?dataset)
}