prefix : <http://a.b#>
prefix fn: <http://www.w3.org/2005/xpath-functions#>

SELECT 
   ?countryName 
   ?orderedCountries 
   (strbefore(?orderedCountries,?countryName) as ?substr) 
   ((strlen(?substr) / strlen(?countryName)) + 1 as ?rep) WHERE  {
 ?obs :country ?country .
 BIND (str(?country) as ?countryName)
 BIND (strbefore("abc","b") as ?x)
 { SELECT (GROUP_CONCAT(?country;separator="") as ?orderedCountries) WHERE {
   SELECT ?country ?value WHERE {
     ?obs :value ?value ;
          :country ?country
   } 
   ORDER BY DESC(?value) 
  }
 }
}