# SliceKey components must be subset of the DSD's component
PREFIX rdf:            <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:           <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos:           <http://www.w3.org/2004/02/skos/core#>
PREFIX qb:             <http://purl.org/linked-data/cube#>
PREFIX xsd:            <http://www.w3.org/2001/XMLSchema#>
PREFIX owl:            <http://www.w3.org/2002/07/owl#>
PREFIX eg:             <http://example.com/abbrv-cube/>
prefix cex: 		   <http://purl.org/weso/ontology/computex#> 

CONSTRUCT {
 _:error a cex:Error .
 _:error cex:errorParam 
	[cex:name "slicekey"; cex:value ?slicekey ]  ,
	[cex:name "prop"; cex:value ?prop ]  ,
	[cex:name "dsd"; cex:value ?dsd ]
	.
 _:error cex:msg "SliceKey components must be subset of the DSDs component" .
}
WHERE {
  ?slicekey a qb:SliceKey;
            qb:componentProperty ?prop .
  ?dsd qb:sliceKey ?sliceKey .
  FILTER NOT EXISTS { ?dsd qb:component [qb:componentProperty ?prop] }
}
