prefix : <http://a.b#>
prefix fn: <http://www.w3.org/2005/xpath-functions#>

SELECT ?country ?rank {
 
SELECT * WHERE  {
 ?obs :country ?country .
 BIND (str(?country) as ?countryName)
 { SELECT (GROUP_CONCAT(?country;separator="") as ?orderedCountries) WHERE {
   SELECT ?country ?value WHERE {
     ?obs :value ?value ;
          :country ?country
   } 
   ORDER BY DESC(?value) 
  }
 }
 BIND (strbefore(?orderedCountries,?countryName) as ?substr)
 BIND ((strlen(?substr) / strlen(?countryName)) + 1 as ?rank)
 }
}