prefix country:      <http://data.webfoundation.org/webindex/v2013/country/> 
prefix dataset:      <http://data.webfoundation.org/webindex/v2013/dataset/> 
prefix indicator:    <http://data.webfoundation.org/webindex/v2013/indicator/> 
prefix obs:          <http://data.webfoundation.org/webindex/v2013/observation/> 
prefix organization: <http://data.webfoundation.org/webindex/v2013/organization> 
prefix slice:        <http://data.webfoundation.org/webindex/v2013/slice/> 
prefix ranking:      <http://data.webfoundation.org/webindex/v2013/ranking/> 

prefix afn:			 <http://jena.hpl.hp.com/ARQ/function#>
prefix cex:          <http://purl.org/weso/ontology/computex#> 
prefix owl:          <http://www.w3.org/2002/07/owl#> 
prefix qb:           <http://purl.org/linked-data/cube#>
prefix rdf:          <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
prefix rdfs:         <http://www.w3.org/2000/01/rdf-schema#> 
prefix wi-onto:      <http://data.webfoundation.org/webindex/ontology/> 
prefix xml:          <http://www.w3.org/XML/1998/namespace> 
prefix xsd:          <http://www.w3.org/2001/XMLSchema#> 

CONSTRUCT {
 [] cex:ranking 
		   [cex:name "obs" ; cex:value ?obs ] ,
		   [cex:name "existingValue"; cex:value ?existingValue ] ,
		   [cex:name "x1"; cex:value ?x1 ] ,
		   [cex:name "x2"; cex:value ?x2 ] ,
		   [cex:name "lsObs"; cex:value ?lsObs ] ,
		   [cex:name "avgGrowth"; cex:value ?avgGrowth ] 
		   .
} WHERE { 
 ?obs cex:computation 
   [ a cex:AverageGrowth2 ;
	   cex:observations ?lsObs ; 						   
   ] ;
   cex:value ?existingValue .
 ?lsObs rdf:first ?x1 .
 ?lsObs rdf:rest/rdf:first ?x2 .
 ?x1 cex:value ?v1 .
 ?x2 cex:value ?v2 .
 BIND (?v1 * (?v1 / ?v2) as ?avgGrowth)
}
