PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX sdmx-concept:  <http://purl.org/linked-data/sdmx/2009/concept#>
PREFIX sdmx-attribute: <http://purl.org/linked-data/sdmx/2009/attribute#>
PREFIX wi-onto:  <http://data.webfoundation.org/webindex/ontology/>
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX cex: <http://purl.org/weso/ontology/computex#>
PREFIX dcterms:  <http://purl.org/dc/terms/>
PREFIX wi-org: <http://data.webfoundation.org/webindex/v2013/organization/>
PREFIX wi-slice:  <http://data.webfoundation.org/webindex/v2013/slice/> 

CONSTRUCT {
	?y rdf:type qb:Slice .
	?y cex:indicator ?indicator .
	?y wi-onto:ref-year ?year .
	?y qb:observation ?obs .
	?y qb:sliceStructure wi-onto:sliceByArea .
} WHERE {
	?y rdf:type qb:Slice .
	?y wi-onto:ref-indicator ?indicator .
	?y wi-onto:ref-year ?year .
	?y qb:observation ?obs .
	?obs wi-onto:value ?value .
	FILTER(CONTAINS(str(?y), "-Raw"))
}