PREFIX rdf:            <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX qb:             <http://purl.org/linked-data/cube#>

CONSTRUCT {
    ?o rdf:type qb:Observation .
} WHERE {
    [] qb:observation ?o .
}

